# -*- coding: utf-8 -*-
"""Clustering Project Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLsinIW0o8d5LAw-mcUjcfWljx7v7jUC
"""

import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("https://raw.githubusercontent.com/Sanchitbhadani-1/Unsupervised-Clustering-Machine-Learning/refs/heads/main/Final-Project/CC%20GENERAL.csv")

df.head()

plt.figure(figsize=(12,10))
corr = df.drop('CUST_ID', axis=1).corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap of Numerical Features")
plt.show()

df = df.drop(["CUST_ID", "ONEOFF_PURCHASES", "PURCHASES_INSTALLMENTS_FREQUENCY", "CASH_ADVANCE_TRX"], axis=1)

df.shape

df.describe()

df.dtypes

df.isnull().sum()

df.duplicated().sum()

df['CREDIT_LIMIT'].fillna(df['CREDIT_LIMIT'].median(), inplace=True)

df['MINIMUM_PAYMENTS'].fillna(df['MINIMUM_PAYMENTS'].median(), inplace=True)

features_graphed = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE', 'CREDIT_LIMIT', 'PRC_FULL_PAYMENT']

for col in features_graphed:
    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    sns.histplot(df[col], kde=True)
    plt.title(f'{col} Distribution')

    plt.subplot(1,2,2)
    sns.boxplot(x=df[col])
    plt.title(f'{col} Boxplot')

    plt.tight_layout()
    plt.show()

import numpy as np

for col in features_graphed:
    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    sns.histplot(np.log1p(df[col]), kde=True)
    plt.title(f'{col} (Log Scale)')

    plt.subplot(1,2,2)
    sns.boxplot(x=np.log1p(df[col]))
    plt.title(f'{col} Boxplot (Log Scale)')

    plt.tight_layout()
    plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

features_8 = [
'BALANCE',
'PURCHASES',
'INSTALLMENTS_PURCHASES',
'CASH_ADVANCE',
'PURCHASES_FREQUENCY',
'CREDIT_LIMIT',
'PRC_FULL_PAYMENT',
'TENURE'
]

# Log transform for better visualization
df_log = df[features_8].apply(np.log1p)

sns.pairplot(df_log, diag_kind='kde', corner=True)
plt.suptitle('Pairwise Relationships of All Selected Features (Log Transformed)', y=1.02)
plt.show()

final_features = [
    'BALANCE',
    'BALANCE_FREQUENCY',
    'PURCHASES',
    'INSTALLMENTS_PURCHASES',
    'CASH_ADVANCE',
    'PURCHASES_FREQUENCY',
    'ONEOFF_PURCHASES_FREQUENCY',
    'CASH_ADVANCE_FREQUENCY',
    'PURCHASES_TRX',
    'CREDIT_LIMIT',
    'PAYMENTS',
    'MINIMUM_PAYMENTS',
    'PRC_FULL_PAYMENT',
    'TENURE'
]

df_final = df[final_features]

df_final

outlier_summary = {}

for col in final_features:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    outlier_summary[col] = len(outliers)

# Show results
outlier_summary_df = pd.DataFrame.from_dict(outlier_summary, orient='index', columns=['Outlier Count'])
outlier_summary_df.sort_values(by='Outlier Count', ascending=False)

from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit and transform
df_scaled = scaler.fit_transform(df_final)

# Convert back to DataFrame (important for readability)
df_scaled = pd.DataFrame(df_scaled, columns=final_features)

df_scaled.head()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

wcss = []

k_values = range(2, 7)

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(df_scaled)
    wcss.append(kmeans.inertia_)

# Plot
plt.figure(figsize=(8,5))
plt.plot(k_values, wcss, marker='o')
plt.title('Elbow Method (WCSS vs k)')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('WCSS (Inertia)')
plt.xticks(k_values)
plt.grid(True)
plt.show()

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

scores = []

k_values = range(2, 7)

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(df_scaled)

    score = silhouette_score(df_scaled, labels)
    scores.append(score)

    print(f"k = {k}, Silhouette Score = {score}")

import matplotlib.pyplot as plt

plt.plot(k_values, scores, marker='o')
plt.title('Silhouette Score vs k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.show()

from sklearn.cluster import KMeans
import pandas as pd

# K-Means model
kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    max_iter=300,
    n_init=10
)

# Fit model and get cluster labels
kmeans_labels = kmeans.fit_predict(df_scaled)

# Add labels to a copy of your original data
df_kmeans = df.copy()
df_kmeans['KMeans_Cluster'] = kmeans_labels

# Cluster sizes
cluster_sizes = df_kmeans['KMeans_Cluster'].value_counts().sort_index()

print("Cluster sizes:")
print(cluster_sizes)
print("\nInertia (WCSS):", kmeans.inertia_)

cluster_summary = cluster_sizes.reset_index()
cluster_summary.columns = ['Cluster', 'Number of Samples']
cluster_summary

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

plt.figure(figsize=(8,6))
plt.scatter(df_pca[:, 0], df_pca[:, 1], c=kmeans_labels)
plt.title('K-Means Clusters (PCA Projection)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# PCA transform
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Transform cluster centers into PCA space
centers_pca = pca.transform(kmeans.cluster_centers_)

# Plot data points
plt.figure(figsize=(8,6))
plt.scatter(df_pca[:, 0], df_pca[:, 1], c=kmeans_labels, alpha=0.6)

# Plot cluster centers
plt.scatter(centers_pca[:, 0], centers_pca[:, 1], marker='X', s=200)

plt.title('K-Means Clusters with Cluster Centers (PCA)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')

plt.show()

cluster_means = df_kmeans.groupby('KMeans_Cluster')[final_features].mean()
cluster_means

cluster_means_scaled = df_scaled.copy()
cluster_means_scaled['Cluster'] = kmeans_labels

cluster_profile = cluster_means_scaled.groupby('Cluster').mean()
cluster_profile

# Map K-Means cluster numbers to A/B/C/D labels
cluster_map = {
    1: 'A',  # Low activity users
    3: 'B',  # High spenders
    2: 'C',  # High balance / cash-advance users
    0: 'D'   # Moderate / frequent-paying users
}

df_kmeans['Cluster_Label'] = df_kmeans['KMeans_Cluster'].map(cluster_map)

cluster_profile = cluster_profile.rename(index=cluster_map)
cluster_profile

# Map K-Means cluster numbers to A/B/C/D
cluster_map = {
    0: 'D',
    1: 'A',
    2: 'C',
    3: 'B'
}

# Add letter labels
df_kmeans['Cluster_Label'] = df_kmeans['KMeans_Cluster'].map(cluster_map)

# Count size of each lettered cluster
cluster_size_by_letter = (
    df_kmeans['Cluster_Label']
    .value_counts()
    .reindex(['A', 'B', 'C', 'D'])
    .reset_index()
)

cluster_size_by_letter.columns = ['Cluster', 'Count']

cluster_size_by_letter

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# PCA transform
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Transform cluster centers into PCA space
centers_pca = pca.transform(kmeans.cluster_centers_)

# Your cluster mapping
cluster_map = {
    1: 'A',  # Low activity
    3: 'B',  # High spenders
    2: 'C',  # High balance / cash advance
    0: 'D'   # Moderate users
}

# Plot points
plt.figure(figsize=(8,6))
plt.scatter(df_pca[:, 0], df_pca[:, 1], c=kmeans_labels, alpha=0.6)

# Plot centers
plt.scatter(centers_pca[:, 0], centers_pca[:, 1], marker='X', s=250)

# Label each center with A/B/C/D
for i, (x, y) in enumerate(centers_pca):
    label = cluster_map[i]
    plt.text(x, y, label, fontsize=14, fontweight='bold', ha='center', va='center')

plt.title('K-Means Clusters with Labeled Centers')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')

plt.show()

# K-Means cluster sizes
cluster_counts = df_kmeans['KMeans_Cluster'].value_counts().sort_index()

# Percentages
cluster_percent = (cluster_counts / len(df_kmeans)) * 100

cluster_summary = pd.DataFrame({
    'Cluster': cluster_counts.index,
    'Count': cluster_counts.values,
    'Percentage (%)': cluster_percent.values
})

cluster_summary

from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

# Create linkage matrix (Ward is best for your case)
linked = linkage(df_scaled, method='ward')

# Plot dendrogram
plt.figure(figsize=(12,6))
dendrogram(linked)

plt.title('Dendrogram (Hierarchical Clustering)')
plt.xlabel('Data Points')
plt.ylabel('Distance')

plt.show()

from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
import matplotlib.pyplot as plt
import pandas as pd

# Step 1: Linkage (Ward method)
linked = linkage(df_scaled, method='ward')

# Step 2: Dendrogram (use sample for readability)
sample = df_scaled.sample(1000, random_state=42)

plt.figure(figsize=(12,6))
dendrogram(linkage(sample, method='ward'))

plt.title('Dendrogram (Hierarchical Clustering)')
plt.xlabel('Sample Data Points')
plt.ylabel('Distance')
plt.show()

hierarchical_labels = fcluster(linked, t=4, criterion='maxclust')

from scipy.cluster.hierarchy import linkage, fcluster
from sklearn.metrics import silhouette_score

# Step 1: Create linkage
linked = linkage(df_scaled, method='ward')

# Step 2: Get cluster labels (k = 4)
hierarchical_labels = fcluster(linked, t=4, criterion='maxclust')

# Step 3: Compute silhouette score
hierarchical_silhouette = silhouette_score(df_scaled, hierarchical_labels)

print("Hierarchical Silhouette Score:", hierarchical_silhouette)

scores_hier = []
k_values = range(2, 7)

for k in k_values:
    labels = fcluster(linked, t=k, criterion='maxclust')
    score = silhouette_score(df_scaled, labels)
    scores_hier.append(score)

    print(f"k = {k}, Hierarchical Silhouette Score = {score}")

import matplotlib.pyplot as plt

plt.plot(k_values, scores_hier, marker='o')
plt.title('Hierarchical Silhouette Score vs k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.show()

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# PCA transform (same as K-Means)
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Plot hierarchical clusters
plt.figure(figsize=(8,6))
plt.scatter(df_pca[:, 0], df_pca[:, 1], c=hierarchical_labels, alpha=0.6)

plt.title('Hierarchical Clusters (PCA Projection)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')

plt.show()

df_hierarchical = df.copy()
df_hierarchical['Cluster'] = hierarchical_labels

hier_means = df_hierarchical.groupby('Cluster')[final_features].mean()
hier_means

# Count hierarchical cluster sizes
cluster_counts = (
    df_hierarchical['Cluster']
    .value_counts()
    .sort_index()
)

# Percentages
cluster_percent = (cluster_counts / len(df_hierarchical)) * 100

# Combine into one table
hier_cluster_summary = pd.DataFrame({
    'Cluster': cluster_counts.index,
    'Count': cluster_counts.values,
    'Percentage (%)': cluster_percent.values
})

hier_cluster_summary

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import pandas as pd

# PCA transform
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Put PCA coordinates into a DataFrame
df_pca_df = pd.DataFrame(df_pca, columns=['PC1', 'PC2'])
df_pca_df['Hierarchical_Cluster'] = hierarchical_labels

# Compute "cluster centers" as mean PCA position of each hierarchical cluster
hier_centers = df_pca_df.groupby('Hierarchical_Cluster')[['PC1', 'PC2']].mean()

# Plot data points
plt.figure(figsize=(8,6))
plt.scatter(df_pca[:, 0], df_pca[:, 1], c=hierarchical_labels, alpha=0.6)

# Plot hierarchical cluster centers
plt.scatter(hier_centers['PC1'], hier_centers['PC2'], marker='X', s=200)

plt.title('Hierarchical Clusters with Cluster Centers (PCA)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')

plt.show()

import pandas as pd

# Step 1: Use your scaled data (already standardized)
df_hier_scaled = df_scaled.copy()

# Step 2: Add hierarchical cluster labels
df_hier_scaled['Cluster'] = hierarchical_labels

# Step 3: Compute mean of each feature per cluster
hier_cluster_profile = df_hier_scaled.groupby('Cluster').mean()

hier_cluster_profile

hier_map = {
    4: 'A',  # Low activity users
    1: 'B',  # High spenders
    3: 'C',  # High balance / cash advance users
    2: 'D'   # Moderate / frequent-paying users
}

df_hierarchical['Cluster_Label'] = df_hierarchical['Cluster'].map(hier_map)

df_hierarchical.groupby('Cluster_Label')[final_features].mean()

df_hier_scaled['Cluster_Label'] = df_hier_scaled['Cluster'].map(hier_map)

# Step 4: Group by labeled clusters
hier_cluster_profile = df_hier_scaled.groupby('Cluster_Label').mean()

hier_cluster_profile

# Counts
cluster_counts = df_hierarchical['Cluster_Label'].value_counts()

# Percentages
cluster_percent = (cluster_counts / len(df_hierarchical)) * 100

# Combine into one table
cluster_summary = pd.DataFrame({
    'Count': cluster_counts,
    'Percentage (%)': cluster_percent
})

cluster_summary

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# PCA transform
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Put PCA coords into a dataframe
df_hier_plot = pd.DataFrame(df_pca, columns=['PC1', 'PC2'])
df_hier_plot['Hierarchical_Cluster'] = hierarchical_labels

# Map hierarchical cluster numbers to A/B/C/D
# IMPORTANT: adjust these numbers only if your hierarchical cluster means differ
hier_map = {
    1: 'A',  # Low activity users
    4: 'B',  # High spenders
    3: 'C',  # High balance / cash advance users
    2: 'D'   # Moderate / frequent-paying users
}

df_hier_plot['Cluster_Label'] = df_hier_plot['Hierarchical_Cluster'].map(hier_map)

# Compute "center" of each hierarchical cluster in PCA space
hier_centers = df_hier_plot.groupby('Hierarchical_Cluster')[['PC1', 'PC2']].mean()

# Scatter plot
plt.figure(figsize=(8,6))
plt.scatter(df_hier_plot['PC1'], df_hier_plot['PC2'], c=df_hier_plot['Hierarchical_Cluster'], alpha=0.6)

# Plot cluster center markers
plt.scatter(hier_centers['PC1'], hier_centers['PC2'], marker='X', s=250)

# Label each center with A/B/C/D
for cluster_num, row in hier_centers.iterrows():
    label = hier_map[cluster_num]
    plt.text(row['PC1'], row['PC2'], label, fontsize=14, fontweight='bold',
             ha='center', va='center')

plt.title('Hierarchical Clusters with Labeled Group Centers')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

import pandas as pd

# The silhouette score for KMeans with k=4 is the 3rd element (index 2) in the scores list
# as k_values started from 2.
kmeans_silhouette = scores[2]

comparison_table = pd.DataFrame({
    'Algorithm': ['K-Means', 'Hierarchical'],
    'Clusters (k)': [4, 4],
    'ARI Score': ['N/A', 'N/A'],
    'Inertia (WCSS)': [kmeans.inertia_, 'N/A'],
    'Silhouette Score': [kmeans_silhouette, hierarchical_silhouette]
})

comparison_table

import matplotlib.pyplot as plt

algorithms = ['K-Means', 'Hierarchical']
scores = [kmeans_silhouette, hierarchical_silhouette]

plt.figure(figsize=(6,4))
plt.bar(algorithms, scores)

plt.title('Silhouette Score Comparison')
plt.ylabel('Silhouette Score')
plt.xlabel('Algorithm')

plt.show()

plt.figure(figsize=(8,5))

# Reconstructing K-Means silhouette scores from previous calculations (cell BoFIopWrver-)
kmeans_scores_over_k = [
    0.29267696504664603, # k=2
    0.2527068970042622,  # k=3
    0.180746879706373,   # k=4
    0.18974841635587048, # k=5
    0.2107901438468051   # k=6
]

plt.plot(range(2,7), kmeans_scores_over_k, marker='o', label='K-Means')
plt.plot(range(2,7), scores_hier, marker='o', label='Hierarchical')

plt.title('Silhouette Score vs Number of Clusters')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.legend()

plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12,5))

# K-Means
axes[0].scatter(df_pca[:,0], df_pca[:,1], c=kmeans_labels, alpha=0.6)
axes[0].set_title('K-Means Clusters')

# Hierarchical
axes[1].scatter(df_pca[:,0], df_pca[:,1], c=hierarchical_labels, alpha=0.6)
axes[1].set_title('Hierarchical Clusters')

plt.show()