# -*- coding: utf-8 -*-
"""Clustering Algorithims Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpatP4bYopUWhfmNBUtjb6IbTm3Yu91Q
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from matplotlib import pyplot as plt

# generating dummy data of 500 records with 4 clusters
features, labels = make_blobs(n_samples=500, centers=4,
cluster_std = 2.00)
# plotting the dummy data
plt.scatter(features[:,0], features[:,1])

# performing kmeans clustering using KMeans class
km_model = KMeans(n_clusters=4)
km_model.fit(features)

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
# adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels, km_model.labels_))

#printing centroid values
print(km_model.cluster_centers_)

# printing predicted label values
print(km_model.labels_)

#print the data points
plt.scatter(features[:,0], features[:,1], c= km_model.labels_, cmap='rainbow')

#print the centroids
plt.scatter(km_model.cluster_centers_[:, 0], km_model.cluster_centers_[:, 1], s=100, c='black')

#print actual datapoints
plt.scatter(features[:,0], features[:,1], c= labels, cmap='rainbow')

import seaborn as sns
iris_df = sns.load_dataset("iris")
iris_df.head()

# dividing data into features and labels
features = iris_df.drop(["species"], axis = 1)
labels = iris_df.filter(["species"], axis = 1)
features.head()

# training KMeans model
features = features.values
km_model = KMeans(n_clusters=4)
km_model.fit(features)

print(km_model.labels_)

#print the data points
plt.scatter(features[:,0], features[:,1], c=km_model.labels_, cmap='rainbow')

#print the centroids
plt.scatter(km_model.cluster_centers_[:, 0], km_model.cluster_centers_[:, 1], s=100, c='black')

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
# adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels_num, km_model.labels_))

# training KMeans on K values from 1 to 1 0
loss =[]
for i in range(1, 11) :
  km = KMeans(n_clusters = i).fit(features)
  loss.append(km.inertia_ )

#printing loss against number of clusters
import matplotlib.pyplot as plt
plt.plot(range(1, 11), loss)
plt.title('Finding Optimal Clusters via Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('loss')
plt.show( )

# training KMeans with 3 clusters
km_model = KMeans(n_clusters=3)
km_model.fit(features)

#print the data points with predicted labels
plt.scatter(features[:,0], features[:,1], c= km_model.labels_, cmap='rainbow')

#print the predicted centroids
plt.scatter(km_model.cluster_centers_[:, 0], km_model.cluster_centers_[:, 1], s=100, c='black')

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels = le.fit_transform(labels)

#print the data points with original labels
plt.scatter(features[:,0], features[:,1], c= labels, cmap='rainbow')

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
# adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels_num, km_model.labels_))