# -*- coding: utf-8 -*-
"""Bank Note Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAPegiK8FLY0xWE9KMUCQ32kX5xm80Ob
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import make_blobs
from matplotlib import pyplot as plt
# %matplotlib inline

# generating dummy data of 10 records with 2 clusters
features, labels = make_blobs(n_samples=10, centers=2, cluster_std = 2.00)
# plotting the dummy data
plt.scatter(features[:,0], features[:,1])
#adding numbers to data points
annots = range(1, 11)
for label, x, y in zip(annots, features[:, 0], features[:, 1]):
  plt.annotate(label, xy=(x, y), xytext= (-3, 3), textcoords='offset points', ha='right', va='bottom')
plt.show( )

from scipy.cluster.hierarchy import dendrogram, linkage
dendos = linkage(features, 'single')
annots = range(1, 11)
dendrogram(dendos, orientation='top', labels=annots, distance_sort='descending', show_leaf_counts=True)
plt.show( )

from sklearn.cluster import AgglomerativeClustering
# training agglomerative clustering model
hc_model = AgglomerativeClustering(n_clusters=2, metric='euclidean', linkage='ward')
hc_model.fit_predict(features)

plt.scatter(features[:,0], features[:,1], c= hc_model.labels_, cmap='rainbow')

features, labels = make_blobs(n_samples=500, centers=4, cluster_std = 2.00)
#plotting the dummy data
plt.scatter(features[:,0], features[:,1])

# performing clustering using AgglomerativeClustering class
hc_model = AgglomerativeClustering(n_clusters=4, metric='euclidean', linkage='ward')
hc_model.fit_predict(features)

#print the data points
plt.scatter(features[:,0], features[:,1], c=hc_model.labels_, cmap='rainbow')

plt.scatter(features[:,0], features[:,1], c=labels, cmap='rainbow')

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
# adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels, hc_model.labels_))

import seaborn as sns
df = pd.read_csv("https://raw.githubusercontent.com/Sanchitbhadani-1/Exploring-Pandas/main/Pandas-Summative/banknote(in).csv")
df.head()

# dividing data into features and labels
features = df.drop(["class"], axis = 1)
labels = df.filter(["class"], axis = 1)
features.head()

from sklearn.cluster import KMeans
km_model = KMeans(n_clusters=2)
km_model.fit(features)

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
# adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels_num, km_model.labels_))

#printing centroid values
print(km_model.cluster_centers_)

# printing predicted label values
print(km_model.labels_)

#print the data points
plt.scatter(features.values[:,0], features.values[:,1], c= km_model.labels_, cmap='rainbow')

#print the centroids
plt.scatter(km_model.cluster_centers_[:, 0], km_model.cluster_centers_[:, 1], s=100, c='black')

#print actual datapoints
plt.scatter(features[:,0], features[:,1], c= labels_num, cmap='rainbow')

# training Hierarchical clustering model
from sklearn.cluster import AgglomerativeClustering
# training agglomerative clustering model
features = features.values
hc_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
hc_model.fit_predict(features)

print(hc_model.labels_)

#print the data points
plt.scatter(features[:,0], features[:,1], c=hc_model.labels_, cmap='rainbow')

# converting categorical labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
# adjusted_rand_score(labels_true,labels_pred)
print("ARI = ", adjusted_rand_score(labels_num, hc_model.labels_))

import scipy.cluster.hierarchy as shc
plt.figure(figsize=(10, 7))
plt.title("Banknote Dendograms" )
dend = shc.dendrogram(shc.linkage(features, method='ward'))

#pring the data points with original labels
plt.scatter(features[:,0], features[:,1],c=labels_num, cmap='rainbow' )