# -*- coding: utf-8 -*-
"""Customer Churn Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xn7t23KpaQNubD9w1v3a8C5lfaWY5ctw
"""

import pandas as pd
import numpy as np
import seaborn as sns

churn_df = pd.read_csv("https://raw.githubusercontent.com/Sanchitbhadani-1/Unsupervised-Clustering-Machine-Learning/refs/heads/main/Customer-Churn-Project/customer_churn(in)%20(1).csv")

churn_df.head()

churn_df = churn_df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

X = churn_df.drop(['Exited'], axis=1)
y = churn_df['Exited']

numerical = X.drop(['Geography', 'Gender'], axis = 1)
numerical.head()

categorical = X.filter(['Geography', 'Gender'])
categorical.head()

cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()

X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.20, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)

from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression()
classifier = log_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
classifier = knn_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=42, n_estimators=500)
classifier = rf_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn import svm
svm_clf = svm.SVC()
classifier = svm_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score
print(cross_val_score(classifier, X, y, cv=5, scoring="accuracy"))

from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=42, n_estimators=500)
classifier = rf_clf.fit(X_train, y_train)
# scaling single record
single_record = sc.transform (X.values[105].reshape(1, -1))
# making predictions on the single record
predicted_churn = classifier.predict(single_record)
print(predicted_churn)

from sklearn.metrics import roc_curve, roc_auc_score
# Get predicted class probabilities for the test set
y_pred_prob = rf_clf.predict_proba(X_test)[:, 1]
# Compute the false positive rate (FPR)
# and true positive rate (TPR) for different classification thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob, pos_label=1)
# Compute the ROC AUC score
roc_auc = roc_auc_score(y_test, y_pred_prob)
roc_auc

# Plot the ROC curve
import matplotlib.pyplot as plt
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc)
# roc curve for tpr = fpr
plt.plot([0, 1], [0, 1], 'k- -', label='Random classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show( )